### ISSUE TITLE
Can't add secrets

### ISSUE THREAD

**Issue by appernetic** [fanderzon/lambdasync#14]
When I try to add a secret such as this:

lambdasync secret secretKey="sk_test_XXXXXXXXX"

I have also tried without ".

I get this message:

## oh noes!
=====================================

Terribly sorry! Lambdasync couldn't do that thing you asked it to do.

**Comment by fanderzon** [comment]
I am 99% sure this problem is because your function is not deployed yet (which is totally my fault because of another bug you reported).

I've added a more helpful error message for this case so that future users who try to run the secret command before deploying their function will know what is going on.

(if you still run into errors with the new version after updating lambdasync 3.1.1, and with a deployed  function feel free to just open another issue) 🙂
